"""
ai_engine/src/config.py
모든 설정값이 여기에 있습니다.
점수가 이상하면 여기 값을 조정하세요.
"""

# 앙상블 가중치 (합 = 1.0)
ANALYZER_WEIGHTS = {
    "clip":      0.55,
    "frequency": 0.30,
    "metadata":  0.15,
}

# is_ai 판정 임계값
AI_THRESHOLD = 0.45

# risk_level 기준
RISK_THRESHOLDS = {
    "HIGH":   0.70,
    "MEDIUM": 0.45,
}

# 영상 전처리
VIDEO_CONFIG = {
    "max_frames":  8,
    "frame_size": (224, 224),
    "supported_formats": [".mp4", ".mov", ".avi", ".mkv", ".webm"],
}

# CLIP 설정
CLIP_CONFIG = {
    "model_name": "ViT-B-32",
    "pretrained": "openai",
    "device":     "cpu",
    "ai_prompts": [
        "an AI generated video",
        "a synthetic video created by artificial intelligence",
        "a video generated by AI tools like Sora or Runway",
        "computer generated imagery video",
        "an artificially generated video clip",
    ],
    "real_prompts": [
        "a real video recorded by a camera",
        "authentic video footage shot by a person",
        "a genuine video captured with a camera",
        "natural video recorded by humans",
        "real life video footage",
    ],
}

# 메타데이터 분석
METADATA_CONFIG = {
    "suspicious_encoders": [
        "runway", "sora", "pika", "stable", "animatediff",
        "deforum", "gen-2", "kling", "cogvideo", "zeroscope",
        "modelscope", "videocrafter", "lavie",
    ],
}

# FFT 분석
FREQUENCY_CONFIG = {
    "high_freq_threshold": 0.15,
}
