"""
ai_engine/src/config.py
모든 설정값이 여기에 있습니다.
점수가 이상하면 여기 값을 조정하세요.
"""

# ── 앙상블 가중치 (합 = 1.0) ──────────────────────────────────────────────
ANALYZER_WEIGHTS = {
    "clip":      0.40,   # CLIP Zero-shot
    "frequency": 0.20,   # FFT 주파수 분석
    "metadata":  0.10,   # 메타데이터
    "temporal":  0.30,   # 시공간 분석 (v2 활성화)
}

# ── is_ai 판정 임계값 ──────────────────────────────────────────────────────
AI_THRESHOLD = 0.50

# ── risk_level 기준 ────────────────────────────────────────────────────────
RISK_THRESHOLDS = {
    "HIGH":   0.70,
    "MEDIUM": 0.45,
}

# ── 영상 전처리 (CLIP/FFT용 균등 프레임) ──────────────────────────────────
VIDEO_CONFIG = {
    "max_frames":  8,
    "frame_size": (224, 224),
    "supported_formats": [".mp4", ".mov", ".avi", ".mkv", ".webm"],
}

# ── 시공간 분석 설정 ───────────────────────────────────────────────────────
TEMPORAL_CONFIG = {
    # 연속 프레임 추출 설정
    "frames_per_segment": 16,    # 구간당 연속 프레임 수
    "long_video_threshold": 30,  # 초 단위: 이 이상이면 2구간, 미만이면 1구간
    "min_frames": 4,             # 최소 프레임 수 (너무 짧은 영상 대비)

    # 광류 분석 지표 가중치 (합 = 1.0)
    "flow_weights": {
        "magnitude_inconsistency": 0.40,  # 이동량 불일치
        "direction_inconsistency": 0.20,  # 방향 불일치
        "frame_difference":        0.20,  # 프레임 차분
        "texture_consistency":     0.10,  # 텍스처 일관성 (LBP)
        "edge_consistency":        0.10,  # 엣지 일관성
    },

    # 임계값 (실제 AI/실제 영상 테스트 후 조정)
    "magnitude_threshold":  5.0,   # 광류 이동량 표준편차 기준
    "direction_threshold":  0.3,   # 방향 불일치 기준
    "diff_threshold":       10.0,  # 프레임 차분 기준
    "texture_threshold":    0.15,  # LBP 불일치 기준
    "edge_threshold":       0.20,  # 엣지 불일치 기준
}

# ── CLIP 설정 ──────────────────────────────────────────────────────────────
CLIP_CONFIG = {
    "model_name": "ViT-B-32",
    "pretrained": "openai",
    "device":     "cpu",
    "ai_prompts": [
        "an AI generated video",
        "a synthetic video created by artificial intelligence",
        "a video generated by AI tools like Sora or Runway",
        "computer generated imagery video",
        "an artificially generated video clip",
    ],
    "real_prompts": [
        "a real video recorded by a camera",
        "authentic video footage shot by a person",
        "a genuine video captured with a camera",
        "natural video recorded by humans",
        "real life video footage",
    ],
}

# ── 메타데이터 분석 ────────────────────────────────────────────────────────
METADATA_CONFIG = {
    "suspicious_encoders": [
        "runway", "sora", "pika", "stable", "animatediff",
        "deforum", "gen-2", "kling", "cogvideo", "zeroscope",
        "modelscope", "videocrafter", "lavie",
    ],
}

# ── FFT 분석 ───────────────────────────────────────────────────────────────
FREQUENCY_CONFIG = {
    "high_freq_threshold": 0.75,
}